:sparkles: feat: add hyren
EurekaScratch/charlotte pull request #36
Opened 2024-04-22 14:15 UTC by FurryR

# Proposed Changes

- Added [Hyren](https://github.com/FurryR/hyren) as an addons.

2024-04-22 15:43 UTC, SimonShiki requested changes
for netlify build issues, I will resolve it until it can be merged.
Charlotte packs **all** addons into **one** script file so there's no way loading an addon asynchronously. The current plan is to separate addons from Charlotte itself and execute them by downloading them into IndexedDB (although I am not sure how safe this approach is)

2024-04-22 15:43 UTC, SimonShiki commented on .eslintignore
> +/addons/hyren/hyren
add new line

2024-04-22 15:43 UTC, SimonShiki commented on package.json
> +    "hyren:init": "cd ./addons/hyren/hyren && git submodule update --init && cd scratch-render && npm ci && cd .. && npm ci && npm run build:injector",
use pnpm instead

2024-04-22 15:43 UTC, SimonShiki commented on package.json
> +}
add new line

2024-04-23 14:24 UTC, FurryR commented on package.json
> +    "hyren:init": "cd ./addons/hyren/hyren && git submodule update --init && cd scratch-render && npm ci && cd .. && npm ci && npm run build:injector",
as hyren is using `npm` as package manager (its scripts also used npm), im not sure about the side-effect of changing manager to `pnpm`.
I will still consider that.

2024-04-26 14:36 UTC, SimonShiki approved these changes

2024-04-26 14:37 UTC, merged